### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ajsb85** [blackvladimir/geda2kicad#1]
```python
$ python pcb2kicad.py blackmagic_mini.pcb

Traceback (most recent call last):
  File "pcb2kicad.py", line 195, in <module>
    pcb = Pcb(infile)
  File "/home/ajsb85/dev/geda2kicad/pcb.py", line 328, in __init__
    self.layers.append(Layer(item))
  File "/home/ajsb85/dev/geda2kicad/pcb.py", line 209, in __init__
    self.flags = item.attributes[2].flags()
IndexError: list index out of range
```

[blackmagic_mini.zip](https://github.com/blackvladimir/geda2kicad/files/9456132/blackmagic_mini.zip)

**Comment by blackvladimir** [comment]
fixed by: 5ff4c571243c277edbcd10edf687f56f0e8fe959
