### ISSUE TITLE
Unknown item Cursor

### ISSUE THREAD

**Issue by ajsb85** [blackvladimir/geda2kicad#2]
```python
$ python pcb2kicad.py blackmagic_mini.pcb

Traceback (most recent call last):
  File "pcb2kicad.py", line 195, in <module>
    pcb = Pcb(infile)
  File "/home/ajsb85/dev/geda2kicad/pcb.py", line 334, in __init__
    raise Exception("unknown item %s" % item.name)
Exception: unknown item Cursor
```

[blackmagic_mini.zip](https://github.com/blackvladimir/geda2kicad/files/9456132/blackmagic_mini.zip)

**Comment by blackvladimir** [comment]
fixed by 03bfea5d05a2072f9d195973ada6806eb1b21f44
