### ISSUE TITLE
Unknown units

### ISSUE THREAD

**Issue by ajsb85** [blackvladimir/geda2kicad#3]
```python
$ python pcb2kicad.py blackmagic_mini.pcb

Traceback (most recent call last):
  File "pcb2kicad.py", line 195, in <module>
    pcb = Pcb(infile)
  File "/home/ajsb85/dev/geda2kicad/pcb.py", line 294, in __init__
    self.gridStep = item.attributes[0].distance()
  File "/home/ajsb85/dev/geda2kicad/parsepcb.py", line 74, in distance
    raise Exception("unknown units")
Exception: unknown units
```

[blackmagic_mini.zip](https://github.com/blackvladimir/geda2kicad/files/9456132/blackmagic_mini.zip)

**Comment by blackvladimir** [comment]
fixed by: 26b543e4269c49a724366154888d8feb65cf0055
